# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-10 06:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axf', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('useraccount', models.CharField(max_length=200, unique=True)),
                ('userpasswd', models.CharField(max_length=200)),
                ('username', models.CharField(max_length=200)),
                ('userphone', models.CharField(max_length=200)),
                ('useradderss', models.CharField(max_length=200)),
                ('userimg', models.CharField(max_length=200)),
                ('userrank', models.IntegerField()),
                ('usertoken', models.CharField(max_length=200)),
            ],
        ),
    ]
