# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-10 20:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axf', '0002_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('useraccount', models.CharField(max_length=200)),
                ('productid', models.CharField(max_length=200)),
                ('productnum', models.IntegerField()),
                ('productprice', models.CharField(max_length=200)),
                ('ischose', models.BooleanField(default=True)),
                ('productimg', models.CharField(max_length=200)),
                ('productname', models.CharField(max_length=200)),
                ('orderid', models.CharField(default='0', max_length=200)),
                ('isdelete', models.BooleanField(default=False)),
            ],
        ),
    ]
